### PR TITLE
Openmath instruct

### PR DESCRIPTION
**Pull request by Mistobaan**
WIP of #145

### CODE REVIEW

**Comment by Dahoas** [comment]
Any update on this?

**Comment by Dahoas** [comment]
closes #145

**Comment by Dahoas** [comment]
@Mistobaan I should have asked you to make a pr adding the tags `SYNTH` and `DATASET` into the `categories.json` file before merging this pr. Can you do this?

**Comment by Mistobaan** [comment]
yes!

**Pull request merged**
